### ISSUE TITLE
failed to compile when running "yarn dev"

### ISSUE THREAD

**Issue by bobmoff** [octref/veturpack#9]
cloned the repo

ran "yarn" and "yarn dev"

getting this result

```
 ERROR  Failed to compile with 2 errors                                                                                                                                                             11:19:16

 error  in ./client/components/App.vue

Module build failed: Error:

Vue packages version mismatch:

- vue@2.5.3
- vue-template-compiler@2.5.2

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/bobmoff/Projects/veturpack/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/bobmoff/Projects/veturpack/node_modules/vue-loader/lib/parser.js:1:80)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)

 @ ./client/app.js 3:0-35
 @ ./client/index.js
 @ multi webpack-hot-middleware/client?reload=true ./client/index.js

 error  in ./client/views/Home.vue

Module build failed: Error:

Vue packages version mismatch:

- vue@2.5.3
- vue-template-compiler@2.5.2

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/bobmoff/Projects/veturpack/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/bobmoff/Projects/veturpack/node_modules/vue-loader/lib/parser.js:1:80)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)

 @ ./client/router/index.js 3:0-33
 @ ./client/app.js
 @ ./client/index.js
 @ multi webpack-hot-middleware/client?reload=true ./client/index.js

> VuePack is running at http://localhost:4000
```

and this when visiting the url

```
Error: no such file or directory
    at MemoryFileSystem.readFileSync (/Users/bobmoff/Projects/veturpack/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at devMiddleWare.waitUntilValid (/Users/bobmoff/Projects/veturpack/build/server.js:47:22)
    at Object.ready (/Users/bobmoff/Projects/veturpack/node_modules/webpack-dev-middleware/lib/Shared.js:166:29)
    at Function.waitUntilValid (/Users/bobmoff/Projects/veturpack/node_modules/webpack-dev-middleware/lib/Shared.js:213:10)
    at app.get (/Users/bobmoff/Projects/veturpack/build/server.js:46:17)
    at Layer.handle [as handle_request] (/Users/bobmoff/Projects/veturpack/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/bobmoff/Projects/veturpack/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/bobmoff/Projects/veturpack/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/bobmoff/Projects/veturpack/node_modules/express/lib/router/layer.js:95:5)
    at /Users/bobmoff/Projects/veturpack/node_modules/express/lib/router/index.js:281:22
    at param (/Users/bobmoff/Projects/veturpack/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/bobmoff/Projects/veturpack/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/bobmoff/Projects/veturpack/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/bobmoff/Projects/veturpack/node_modules/express/lib/router/index.js:275:10)
    at middleware (/Users/bobmoff/Projects/veturpack/node_modules/webpack-hot-middleware/middleware.js:26:48)
    at Layer.handle [as handle_request] (/Users/bobmoff/Projects/veturpack/node_modules/express/lib/router/layer.js:95:5)
```

i am running on macOS Sierra 10.13.1 (17B1003)

**Comment by bobmoff** [comment]
Just like the error message says, if i update  "vue-template-compiler" to "2.5.3" to match the vue version ,it works.

Maybe this project should do this as well ? or maybe if these packages (vue and vue-template-compiler) are released together in sync, just let vue also be dynamic by using the "^2.5.3" .. ?

**Comment by octref** [comment]
Thanks, I have no idea why I locked Vue version. Probably while waiting for Vue's TS declaration files in 2.4.
